#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

enum installation_errors {
  ALLEGRO_INSTALLATION_FAILED,
  ENGINE_CONFIG_NOT_FOUND,
  MAIN_DISPLAY_CREATION_FAILED,
  ENGINE_CONFIG_NO_DISPLAY_WIDTH,
  ENGINE_CONFIG_NO_DISPLAY_HEIGHT,
  KEYBOARD_INSTALLATION_FAILED,
  MOUSE_INSTALLATION_FAILED,
  ALLEGRO_PRIMITIVES_ADDON_INSTALLATION_FAILED,
  ENGINE_CONFIG_NO_RENDER_RATE,
  RENDER_TIMER_FAILED
};

void handle_installation_error(int code);
void handle_mainLoop_error(int code);
#endif
